input {
  tcp {
    port => 5000
    codec => json
    type => "docker-logs"
  }
  beats {
    port => 5044
  }
}

filter {
  if [type] == "docker-logs" {
    json {
      source => "message"
      target => "docker"
    }
    date {
      match => ["time", "ISO8601"]
      target => "@timestamp"
    }
    mutate {
      remove_field => ["host", "ecs", "agent", "log", "input", "tags"]
    }
  }
}

output {
  stdout { codec => rubydebug }
  
  elasticsearch {
    hosts => ["elasticsearch-hot:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
    user => ""
    password => ""
  }
}